apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - network-policy.yaml
  - valkey.yaml
  - s3mock.yaml
  - gateway.yaml
  - user-runtime.yaml
  - system-runtime.yaml
  - d1-runtime.yaml
  - do-runtime.yaml
  - scheduler.yaml
  - workflows.yaml
