name = "queue-sink"
main = "src/index.js"
compatibility_date = "2026-04-24"

[[kv_namespaces]]
binding = "KV"
id = "queue-smoketest"

[[queues.consumers]]
queue             = "smoketest"
max_batch_size    = 10
max_batch_timeout = 2
max_retries       = 3
