# Do not restrict graph targets here. Production currently runs ARM64, local/CI
# checks run on x86_64, and target-specific dependencies should stay visible to
# advisories, license, source, and ban checks for every supported Rust target.

[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "MIT",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "allow"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
