apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wdl-local
resources:
  - ../local
  - assets-proxy.yaml
  - ingress.yaml
  - s3mock-network-policy.yaml
patches:
  - path: config-patch.yaml
